spring:
  application:
    name: com.bcadaval.esloveno
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlite:/app-data/db/esloveno.db}
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 6
      minimum-idle: 1
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  sql:
    init:
      mode: always
      schema-locations: classpath:initDatabase.sql
      data-locations: classpath:insertData.sql
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true

server:
  servlet:
    context-path: /

app:
  db:
    path: /app-data/db/esloveno.db
  xml:
    path: /app-data/xml

hibernate:
  dialect: org.hibernate.community.dialect.SQLiteDialect
  hbm2ddl:
    auto: none

logging:
  level:
    root: INFO
    com.bcadaval.esloveno: DEBUG
    org:
      springframework:
        web: INFO  # Desactivar logs DEBUG de requests HTTP
