debug: true
spring:
  application:
    name: com.bcadaval.esloveno
  datasource:
    url: jdbc:sqlite:/data/esloveno.db
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 6
      minimum-idle: 1
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
  sql:
    init:
      mode: always
      schema-locations: classpath:initDatabase.sql
      data-locations: classpath:insertData.sql
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    defer-datasource-initialization: true
app:
  db:
    path: /data/esloveno.db
  xml:
    path: /data/xml
hibernate:
  dialect: org.hibernate.community.dialect.SQLiteDialect
  hbm2ddl:
    auto: none
  show_sql: true
logging:
  level:
    com.bcadaval.esloveno: TRACE
    org:
      hibernate:
        type: TRACE
        orm.jdbc.bind: trace
        SQL: DEBUG
      springframework:
        boot:
         autoconfigure: ERROR
        web: INFO  # Desactivar logs DEBUG de requests HTTP
