-- Tabla para configuración
CREATE TABLE IF NOT EXISTS VARIABLES
(
    CLAVE       TEXT PRIMARY KEY,
    VALOR       TEXT NOT NULL,
    TIPO        TEXT NOT NULL,
    DESCRIPCION TEXT
);

--  Variables por defecto
INSERT
OR REPLACE INTO variables (clave, valor, tipo, descripcion) VALUES
('INTERVALO_INICIAL_SEGUNDOS', '600', 'LONG', 'Segundos para primera repetición (10 min)'),
('INTERVALO_SEGUNDA_SEGUNDOS', '3600', 'LONG', 'Segundos para segunda repetición (1 hora)'),
('INTERVALO_REAPRENDIZAJE_SEGUNDOS', '30', 'LONG', 'Segundos tras fallar (30 seg)'),
('FACTOR_FACILIDAD_MINIMO', '1.3', 'DOUBLE', 'Factor de facilidad mínimo'),
('FACTOR_FACILIDAD_INICIAL', '2.5', 'DOUBLE', 'Factor de facilidad inicial'),
('PENALIZACION_FALLO', '0.2', 'DOUBLE', 'Reducción del factor al fallar'),
('MAX_TARJETAS_NUEVAS_DIA', '20', 'INTEGER', 'Máximo de tarjetas nuevas por día'),
('MAX_TARJETAS_REVISION_DIA', '100', 'INTEGER', 'Máximo de revisiones por día');

-- Tabla para activar/desactivar estructuras
CREATE TABLE IF NOT EXISTS ESTRUCTURA_FRASE_CONFIG
(
    IDENTIFICADOR TEXT PRIMARY KEY,
    ACTIVA        INTEGER DEFAULT 1 -- 1=activa, 0=inactiva
);

CREATE TABLE IF NOT EXISTS ADJETIVO
(
    SLOLEKS_ID  TEXT NOT NULL,
    PRINCIPAL   TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT A_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS ADJETIVO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    GENERO                        TEXT NOT NULL,
    NUMERO                        TEXT NOT NULL,
    CASO                          TEXT NOT NULL,
    GRADO                         TEXT NOT NULL,
    DEFINITUD                     INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT AF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES ADJETIVO (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS PRONOMBRE
(
    SLOLEKS_ID      TEXT NOT NULL,
    PRINCIPAL       TEXT NOT NULL,
    TIPO_PRONOMBRE  TEXT NOT NULL,
    SLOLEKS_KEY     TEXT NOT NULL,
    SIGNIFICADO     TEXT,
    CONSTRAINT P_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS PRONOMBRE_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    PERSONA                       TEXT,
    GENERO                        TEXT,
    NUMERO                        TEXT,
    CASO                          TEXT,
    CLITICO                       INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    SIGNIFICADO                   TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT PF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES PRONOMBRE (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS NUMERAL
(
    SLOLEKS_ID  TEXT NOT NULL,
    PRINCIPAL   TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT N_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS NUMERAL_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    GENERO                        TEXT,
    NUMERO                        TEXT,
    CASO                          TEXT,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT NF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES NUMERAL (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS SUSTANTIVO
(
    SLOLEKS_ID  TEXT NOT NULL,
    PRINCIPAL   TEXT NOT NULL,
    GENERO      TEXT NOT NULL,
    ANIMADO     INTEGER,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT S_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS SUSTANTIVO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    NUMERO                        TEXT NOT NULL,
    CASO                          TEXT NOT NULL,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT SF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES SUSTANTIVO (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS VERBO
(
    SLOLEKS_ID         TEXT NOT NULL,
    PRINCIPAL          TEXT NOT NULL,
    TRANSITIVIDAD      TEXT,
    ASPECTO            TEXT,
    VERBO_OTRO_ASPECTO TEXT,
    SLOLEKS_KEY        TEXT NOT NULL,
    SIGNIFICADO        TEXT,
    CONSTRAINT V_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS VERBO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    FORMA_VERBAL                  TEXT NOT NULL,
    PERSONA                       TEXT,
    NUMERO                        TEXT,
    GENERO                        TEXT,
    NEGATIVO                      INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT VF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES VERBO (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
