-- Tabla para configuración
CREATE TABLE IF NOT EXISTS VARIABLES
(
    CLAVE       TEXT PRIMARY KEY,
    VALOR       TEXT NOT NULL,
    TIPO        TEXT NOT NULL,
    DESCRIPCION TEXT
);

--  Variables por defecto
INSERT
OR REPLACE INTO variables (clave, valor, tipo, descripcion) VALUES
('INTERVALO_INICIAL_SEGUNDOS', '600', 'LONG', 'Segundos para primera repetición (10 min)'),
('INTERVALO_SEGUNDA_SEGUNDOS', '3600', 'LONG', 'Segundos para segunda repetición (1 hora)'),
('INTERVALO_REAPRENDIZAJE_SEGUNDOS', '30', 'LONG', 'Segundos tras fallar (30 seg)'),
('FACTOR_FACILIDAD_MINIMO', '1.3', 'DOUBLE', 'Factor de facilidad mínimo'),
('FACTOR_FACILIDAD_INICIAL', '2.5', 'DOUBLE', 'Factor de facilidad inicial'),
('PENALIZACION_FALLO', '0.2', 'DOUBLE', 'Reducción del factor al fallar'),
('MAX_TARJETAS_NUEVAS_DIA', '20', 'INTEGER', 'Máximo de tarjetas nuevas por día'),
('MAX_TARJETAS_REVISION_DIA', '100', 'INTEGER', 'Máximo de revisiones por día');

-- Tabla para activar/desactivar estructuras
CREATE TABLE IF NOT EXISTS ESTRUCTURA_FRASE_CONFIG
(
    IDENTIFICADOR TEXT PRIMARY KEY,
    ACTIVA        INTEGER DEFAULT 1 -- 1=activa, 0=inactiva
);

CREATE TABLE IF NOT EXISTS ADJETIVO
(
    PRINCIPAL   TEXT NOT NULL,
    ACENTUADO   TEXT,
    SLOLEKS_ID  TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT A_PK PRIMARY KEY (PRINCIPAL)
);
CREATE TABLE IF NOT EXISTS ADJETIVO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    PRINCIPAL                     TEXT NOT NULL,
    GENERO                        TEXT NOT NULL,
    NUMERO                        TEXT NOT NULL,
    CASO                          TEXT NOT NULL,
    GRADO                         TEXT NOT NULL,
    DEFINITUD                     INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT AF_CON_GEN CHECK ("GENERO" IN ('M', 'F', 'N')),
    CONSTRAINT AF_CON_NUM CHECK ("NUMERO" IN ('1', '2', '3')),
    CONSTRAINT AF_CON_CAS CHECK ("CASO" IN ('1', '2', '3', '4', '5', '6')),
    CONSTRAINT AF_CON_GRA CHECK ("GRADO" IN ('P', 'C', 'S')),
    CONSTRAINT AF_UK UNIQUE (PRINCIPAL, GENERO, NUMERO, CASO, GRADO, DEFINITUD),
    CONSTRAINT AF_FK FOREIGN KEY (PRINCIPAL) REFERENCES ADJETIVO (PRINCIPAL) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS PRONOMBRE
(
    PRINCIPAL       TEXT NOT NULL,
    ACENTUADO       TEXT,
    TIPO_PRONOMBRE  TEXT NOT NULL,
    SLOLEKS_ID      TEXT NOT NULL,
    SLOLEKS_KEY     TEXT NOT NULL,
    SIGNIFICADO     TEXT,
    CONSTRAINT P_PK PRIMARY KEY (PRINCIPAL)
);
CREATE TABLE IF NOT EXISTS PRONOMBRE_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    PRINCIPAL                     TEXT NOT NULL,
    PERSONA                       TEXT,
    GENERO                        TEXT,
    NUMERO                        TEXT,
    CASO                          TEXT,
    CLITICO                       INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    SIGNIFICADO                   TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT PF_CON_PER CHECK ("PERSONA" IS NULL OR "PERSONA" IN ('1', '2', '3')),
    CONSTRAINT PF_CON_GEN CHECK ("GENERO" IS NULL OR "GENERO" IN ('M', 'F', 'N')),
    CONSTRAINT PF_CON_NUM CHECK ("NUMERO" IS NULL OR "NUMERO" IN ('1', '2', '3')),
    CONSTRAINT PF_CON_CAS CHECK ("CASO" IS NULL OR "CASO" IN ('1', '2', '3', '4', '5', '6')),
    CONSTRAINT PF_UK UNIQUE (PRINCIPAL, PERSONA, GENERO, NUMERO, CASO, CLITICO),
    CONSTRAINT PF_FK FOREIGN KEY (PRINCIPAL) REFERENCES PRONOMBRE (PRINCIPAL) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS NUMERAL
(
    PRINCIPAL   TEXT NOT NULL,
    ACENTUADO   TEXT,
    SLOLEKS_ID  TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT N_PK PRIMARY KEY (PRINCIPAL)
);
CREATE TABLE IF NOT EXISTS NUMERAL_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    PRINCIPAL                     TEXT NOT NULL,
    GENERO                        TEXT,
    NUMERO                        TEXT,
    CASO                          TEXT,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT NF_CON_GEN CHECK ("GENERO" IS NULL OR "GENERO" IN ('M', 'F', 'N')),
    CONSTRAINT NF_CON_NUM CHECK ("NUMERO" IS NULL OR "NUMERO" IN ('1', '2', '3')),
    CONSTRAINT NF_CON_CAS CHECK ("CASO" IS NULL OR "CASO" IN ('1', '2', '3', '4', '5', '6')),
    CONSTRAINT NF_UK UNIQUE (PRINCIPAL, GENERO, NUMERO, CASO),
    CONSTRAINT NF_FK FOREIGN KEY (PRINCIPAL) REFERENCES NUMERAL (PRINCIPAL) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS SUSTANTIVO
(
    PRINCIPAL   TEXT NOT NULL,
    ACENTUADO   TEXT,
    GENERO      TEXT NOT NULL,
    ANIMADO     INTEGER,
    SLOLEKS_ID  TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT S_CON_GEN CHECK ("GENERO" IN ('M', 'F', 'N')),
    CONSTRAINT S_PK PRIMARY KEY (PRINCIPAL)
);
CREATE TABLE IF NOT EXISTS SUSTANTIVO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    PRINCIPAL                     TEXT NOT NULL,
    NUMERO                        TEXT NOT NULL,
    CASO                          TEXT NOT NULL,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT SF_CON_NUM CHECK ("NUMERO" IN ('1', '2', '3')),
    CONSTRAINT SF_CON_CAS CHECK ("CASO" IN ('1', '2', '3', '4', '5', '6')),
    CONSTRAINT SF_UK UNIQUE (PRINCIPAL, NUMERO, CASO),
    CONSTRAINT SF_FK FOREIGN KEY (PRINCIPAL) REFERENCES SUSTANTIVO (PRINCIPAL) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS VERBO
(
    PRINCIPAL          TEXT NOT NULL,
    ACENTUADO          TEXT,
    TRANSITIVIDAD      TEXT,
    ASPECTO            TEXT NOT NULL,
    VERBO_OTRO_ASPECTO TEXT,
    SLOLEKS_ID         TEXT NOT NULL,
    SLOLEKS_KEY        TEXT NOT NULL,
    SIGNIFICADO        TEXT,
    CONSTRAINT V_CON_TRAN CHECK ("TRANSITIVIDAD" IS NULL OR "TRANSITIVIDAD" IN ('T', 'I', 'A')),
    CONSTRAINT V_CON_ASP CHECK ("ASPECTO" IN ('P', 'I', '*')),
    CONSTRAINT V_PK PRIMARY KEY (PRINCIPAL)
);
CREATE TABLE IF NOT EXISTS VERBO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    PRINCIPAL                     TEXT NOT NULL,
    FORMA_VERBAL                  TEXT NOT NULL,
    PERSONA                       TEXT,
    NUMERO                        TEXT,
    GENERO                        TEXT,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT VF_CON_FV CHECK ("FORMA_VERBAL" IN ('I', 'S', 'P', 'R', 'M', 'F')),
    CONSTRAINT VF_CON_PER CHECK ("PERSONA" IS NULL OR "PERSONA" IN ('1', '2', '3')),
    CONSTRAINT VF_CON_NUM CHECK ("NUMERO" IS NULL OR "NUMERO" IN ('1', '2', '3')),
    CONSTRAINT VF_CON_GEN CHECK ("GENERO" IS NULL OR "GENERO" IN ('M', 'F', 'N')),
    CONSTRAINT VF_FK FOREIGN KEY (PRINCIPAL) REFERENCES VERBO (PRINCIPAL) ON DELETE RESTRICT ON UPDATE RESTRICT
);
