-- Tabla para configuración
CREATE TABLE IF NOT EXISTS VARIABLES
(
    CLAVE       TEXT PRIMARY KEY,
    VALOR       TEXT NOT NULL,
    TIPO        TEXT NOT NULL,
    DESCRIPCION TEXT
);

CREATE TABLE IF NOT EXISTS MENSAJES_FLOTANTES
(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FECHA DATETIME DEFAULT CURRENT_TIMESTAMP,
    MENSAJE TEXT NOT NULL,
    LEIDO INTEGER DEFAULT 0
);

-- Tabla para activar/desactivar estructuras
CREATE TABLE IF NOT EXISTS ESTRUCTURA_FRASE_CONFIG
(
    IDENTIFICADOR TEXT PRIMARY KEY,
    ACTIVA        INTEGER DEFAULT 1 -- 1=activa, 0=inactiva
);

CREATE TABLE IF NOT EXISTS ADJETIVO
(
    SLOLEKS_ID  TEXT NOT NULL,
    PRINCIPAL   TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CONSTRAINT A_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS ADJETIVO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    GENERO                        TEXT NOT NULL,
    NUMERO                        TEXT NOT NULL,
    CASO                          TEXT NOT NULL,
    GRADO                         TEXT NOT NULL,
    DEFINITUD                     INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ELEGIBLE                      INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT AF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES ADJETIVO (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS PRONOMBRE
(
    SLOLEKS_ID      TEXT NOT NULL,
    PRINCIPAL       TEXT NOT NULL,
    TIPO_PRONOMBRE  TEXT NOT NULL,
    SLOLEKS_KEY     TEXT NOT NULL,
    SIGNIFICADO     TEXT,
    CONSTRAINT P_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS PRONOMBRE_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    PERSONA                       TEXT,
    GENERO                        TEXT,
    NUMERO                        TEXT,
    CASO                          TEXT,
    CLITICO                       INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    SIGNIFICADO                   TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ELEGIBLE                      INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT PF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES PRONOMBRE (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS NUMERAL
(
    SLOLEKS_ID  TEXT NOT NULL,
    PRINCIPAL   TEXT NOT NULL,
    SLOLEKS_KEY TEXT NOT NULL,
    SIGNIFICADO TEXT,
    CANTIDAD    INTEGER,
    CONSTRAINT N_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS NUMERAL_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    GENERO                        TEXT,
    NUMERO                        TEXT,
    CASO                          TEXT,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ELEGIBLE                      INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT NF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES NUMERAL (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE TABLE IF NOT EXISTS SUSTANTIVO
(
    SLOLEKS_ID       TEXT NOT NULL,
    PRINCIPAL        TEXT NOT NULL,
    GENERO           TEXT NOT NULL,
    ANIMACIDAD       TEXT,
    CONTABILIDAD     TEXT,
    CLASE_SEMANTICA  TEXT,
    SLOLEKS_KEY      TEXT NOT NULL,
    SIGNIFICADO      TEXT,
    CONSTRAINT S_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS SUSTANTIVO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    NUMERO                        TEXT NOT NULL,
    CASO                          TEXT NOT NULL,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ELEGIBLE                      INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT SF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES SUSTANTIVO (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PARTICULA
(
    SLOLEKS_ID    TEXT NOT NULL,
    PRINCIPAL     TEXT NOT NULL,
    SLOLEKS_KEY   TEXT NOT NULL,
    SIGNIFICADO   TEXT,
    SUBCATEGORIA  TEXT,
    CONSTRAINT PA_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS PARTICULA_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ELEGIBLE                      INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT PAF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES PARTICULA (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS VERBO
(
    SLOLEKS_ID              TEXT NOT NULL,
    PRINCIPAL               TEXT NOT NULL,
    TRANSITIVIDAD           TEXT,
    ASPECTO                 TEXT,
    VERBO_OTRO_ASPECTO      TEXT,
    REQUIERE_SUJETO_ANIMADO TEXT,
    REQUIERE_OBJETO_ANIMADO TEXT,
    SLOLEKS_KEY             TEXT NOT NULL,
    SIGNIFICADO             TEXT,
    CONSTRAINT V_PK PRIMARY KEY (SLOLEKS_ID)
);
CREATE TABLE IF NOT EXISTS VERBO_FLEXION
(
    ID                            INTEGER PRIMARY KEY,
    SLOLEKS_ID                    TEXT NOT NULL,
    PRINCIPAL                     TEXT NOT NULL,
    FORMA_VERBAL                  TEXT NOT NULL,
    PERSONA                       TEXT,
    NUMERO                        TEXT,
    GENERO                        TEXT,
    NEGATIVO                      INTEGER,
    FLEXION                       TEXT NOT NULL,
    ACENTUADO                     TEXT,
    PRONUNCIACION_IPA             TEXT,
    PRONUNCIACION_SAMPA           TEXT,
    FACTOR_FACILIDAD              REAL    DEFAULT 2.5,
    INTERVALO_REPETICION_SEGUNDOS INTEGER DEFAULT 0,
    VECES_CONSECUTIVAS_CORRECTAS  INTEGER DEFAULT 0,
    TOTAL_REVISIONES              INTEGER DEFAULT 0,
    TOTAL_ACIERTOS                INTEGER DEFAULT 0,
    EN_REAPRENDIZAJE              INTEGER DEFAULT 0,
    ELEGIBLE                      INTEGER DEFAULT 0,
    ULTIMA_REVISION               DATETIME,
    PROXIMA_REVISION              DATETIME,
    CONSTRAINT VF_FK FOREIGN KEY (SLOLEKS_ID) REFERENCES VERBO (SLOLEKS_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

-- ========================================================
-- INDICE XML (PARA BÚSQUEDA RÁPIDA)
-- ========================================================
CREATE TABLE IF NOT EXISTS INDICE_XML
(
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    LEMA         TEXT NOT NULL,
    TIPO         TEXT NOT NULL,
    SLOLEKS_ID   TEXT NOT NULL,
    ARCHIVO_NUM  INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_INDICE_XML_LEMA ON INDICE_XML (LEMA);
CREATE INDEX IF NOT EXISTS IDX_INDICE_XML_SLOLEKS ON INDICE_XML (SLOLEKS_ID);

-- ========================================================
-- HISTÓRICO DE RESPUESTAS (ESTADÍSTICAS)
-- ========================================================
CREATE TABLE HISTORICO_RESPUESTAS (
    ID_HISTORICO BIGINT AUTO_INCREMENT PRIMARY KEY,
    SLOLEKS_ID VARCHAR(255) NOT NULL,
    ID INTEGER NOT NULL,
    TIPO_PALABRA VARCHAR(255) NOT NULL,
    TS_RESPUESTA TIMESTAMP NOT NULL,
    ACIERTO BOOLEAN NOT NULL,
    SEGUNDOS_EN_RESPONDER INTEGER
);

CREATE INDEX IDX_HISTORICO_TS ON HISTORICO_RESPUESTAS (TS_RESPUESTA);
CREATE INDEX IDX_HISTORICO_TS_TIPO ON HISTORICO_RESPUESTAS (TS_RESPUESTA, TIPO_PALABRA);

