update PRONOMBRE_FLEXION set significado='yo' where significado is null and persona='1' and numero='1';
update PRONOMBRE_FLEXION set significado='nosotros (2)' where significado is null and persona='1' and numero='2' and genero='M';
update PRONOMBRE_FLEXION set significado='nosotras (2)' where significado is null and persona='1' and numero='2' and genero='F';
update PRONOMBRE_FLEXION set significado='nosotr@s (2)' where significado is null and persona='1' and numero='2' and genero is null;
update PRONOMBRE_FLEXION set significado='nosotros' where significado is null and persona='1' and numero='3' and genero='M';
update PRONOMBRE_FLEXION set significado='nosotras' where significado is null and persona='1' and numero='3' and genero='F';
update PRONOMBRE_FLEXION set significado='nosotr@s' where significado is null and persona='1' and numero='3' and genero is null;
update PRONOMBRE_FLEXION set significado='tú' where significado is null and persona='2' and numero='1';
update PRONOMBRE_FLEXION set significado='vosotros (2)' where significado is null and persona='2' and numero='2' and genero='M';
update PRONOMBRE_FLEXION set significado='vosotras (2)' where significado is null and persona='2' and numero='2' and genero='F';
update PRONOMBRE_FLEXION set significado='vosotres (2)' where significado is null and persona='2' and numero='2' and genero='N';
update PRONOMBRE_FLEXION set significado='vosotr@s (2)' where significado is null and persona='2' and numero='2' and genero is null;
update PRONOMBRE_FLEXION set significado='vosotros' where significado is null and persona='2' and numero='3' and genero='M';
update PRONOMBRE_FLEXION set significado='vosotras' where significado is null and persona='2' and numero='3' and genero='F';
update PRONOMBRE_FLEXION set significado='vosotres' where significado is null and persona='2' and numero='3' and genero='N';
update PRONOMBRE_FLEXION set significado='vosotr@s' where significado is null and persona='2' and numero='3' and genero is null;
update PRONOMBRE_FLEXION set significado='él' where significado is null and persona='3' and numero='1' and genero='M';
update PRONOMBRE_FLEXION set significado='ella' where significado is null and persona='3' and numero='1' and genero='F';
update PRONOMBRE_FLEXION set significado='elle' where significado is null and persona='3' and numero='1' and genero='N';
update PRONOMBRE_FLEXION set significado='ellos (2)' where significado is null and persona='3' and numero='2' and genero='M';
update PRONOMBRE_FLEXION set significado='ellas (2)' where significado is null and persona='3' and numero='2' and genero='F';
update PRONOMBRE_FLEXION set significado='elles (2)' where significado is null and persona='3' and numero='2' and genero='N';
update PRONOMBRE_FLEXION set significado='ellos' where significado is null and persona='3' and numero='3' and genero='M';
update PRONOMBRE_FLEXION set significado='ellas' where significado is null and persona='3' and numero='3' and genero='F';
update PRONOMBRE_FLEXION set significado='elles' where significado is null and persona='3' and numero='3' and genero='N';